image_folder: F:\Lwm_Data\person_data_01\JPEGImages
xml_folder: F:\Lwm_Data\person_data_01\Annotations

train_rate: 0.8
val_rate: 0.1

target_size: 
  - 224
  - 224

image_save_path: F:\Lwm_Code\Visual\Save

# 数据增强
augment: basic
hflip: 0.5
rotate: 0.5
color: 0.5
crop: 0.5